---
linters:
  enable:
    - revive

linters-settings:
  revive:
    rules:
      - name: unused-parameter
        severity: warning
        disabled: false
        exclude: [""]
        arguments:
          - allowRegex: "^_"
